# Generated by Django 4.2.6 on 2024-04-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mealprep", "0004_plannedmeal_alter_ingredient_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedmeal",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
