# Generated by Django 4.2.6 on 2024-04-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mealprep", "0005_plannedmeal_description"),
    ]

    operations = [
        migrations.RemoveField(model_name="meal", name="ingredients",),
        migrations.RemoveField(model_name="mealingredient", name="meal",),
        migrations.AddField(
            model_name="meal",
            name="meal_ingredients",
            field=models.ManyToManyField(to="mealprep.mealingredient"),
        ),
    ]
