# Generated by Django 4.2.6 on 2024-04-30 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "mealprep",
            "0006_remove_meal_ingredients_remove_mealingredient_meal_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="meal", name="meal_ingredients",),
        migrations.AddField(
            model_name="meal",
            name="ingredients",
            field=models.ManyToManyField(
                through="mealprep.MealIngredient", to="mealprep.ingredient"
            ),
        ),
        migrations.AddField(
            model_name="mealingredient",
            name="meal",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="mealprep.meal",
            ),
            preserve_default=False,
        ),
    ]
